[package]
name = "piccolo"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "placeholder crate for the 'piccolo' Lua VM (to be published)"
repository = "https://github.com/kyren/piccolo"
