[package]
name = "piccolo"
version = "0.1.0"
authors = ["kyren <catherine@kyju.org>"]
edition = "2021"
license = "MIT"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
gc-arena = { git = "https://github.com/kyren/gc-arena", branch = "piccolo" }
rand = { version = "0.8", features = ["small_rng"] }
rustc-hash = "1.1"

[dev-dependencies]
clap = { version = "4.2", features = ["cargo"] }
rustyline = "11.0"
